## Build Time
FROM maven:3.9.4-eclipse-temurin-17 as builder

# Workspace
WORKDIR /build

# Cache Config
COPY pom.xml .
COPY src/main/resources ./src/main/resources
RUN mvn dependency:go-offline

# Build
COPY src ./src
RUN mvn clean package -DskipTests

## Run Time
FROM eclipse-temurin:17-jdk

WORKDIR /app
COPY --from=builder /build/target/*.jar /app/ROOT.jar

EXPOSE 8080

CMD ["java", "-jar", "/app/ROOT.jar"]
# CMD ["java", "-Dspring.profiles.active=prod", "-jar", "/app/ROOT.jar"]
