FROM maven:3.9.4-eclipse-temurin-17 as builder

WORKDIR /build
COPY . .

RUN mvn clean package

FROM eclipse-temurin:17-jdk

WORKDIR /app
COPY --from=builder /build/target/*.jar /app/ROOT.jar

EXPOSE 8080

CMD ["java", "-jar", "/app/ROOT.jar"]
# CMD ["java", "-Dspring.profiles.active=prod", "-jar", "/app/ROOT.jar"]
